[pytest]
base_url = https://www.saucedemo.com/

addopts =
    --browser=chromium
    --headed
    --slowmo=1000
    ; --tracing=retain-on-failure
    ; --screenshots=on
    ; --video=retain-on-failure

